<h1>Garçom</h1>

<form action="<?php echo $this->baseUrl('garcom/gravar'); ?>" method="post" enctype="multipart/form-data">
	<input type="hidden" name="id_garcom" value="<?php echo $this->row['id_garcom']; ?>" />
	
	<div class="form-group">
	    <label for="nome">Nome</label>
	    <input type="text" class="form-control" id="nomeGarcom" name="nomeGarcom" value="<?php echo $this->row['nomeGarcom']; ?>">
	</div>
	
	<div class="form-group">
	    <label for="email">E-mail</label>
	    <input type="text" class="form-control" id="email" name="email" value="<?php echo $this->row['email']; ?>">
	</div>
	
	<div class="form-group">
	    <label for="telefone">telefone</label>
	    <input type="text" class="form-control" id="senha" name="telefone" value="<?php echo $this->row['telefone']; ?>">
	</div>
        
        
	
	<div class="text-center">
		<input type="submit" value="Enviar" class="btn btn-success" />
		<a href="<?php echo $this->baseUrl('garcom/index'); ?>" class="btn btn-danger" >Voltar</a>
	</div>
</form>
<script>
    $(function(){
        
        $('#id_uf').change(function(){
            $('#div_municipios').load('<?php echo $this->baseUrl('usuario/carregar-municipio/id_uf/'); ?>' + $('#id_uf').val());
        });
        
    });    
</script>