<h1>Mesas</h1>

<form action="<?php echo $this->baseUrl('mesa/gravar'); ?>" method="post" enctype="multipart/form-data">
    <input type="hidden" name="id_mesa" value="<?php echo $this->row['id_mesa']; ?>" />
	
	<div class="form-group">
	    <label for="numeroMesa">Nr mesa</label>
	    <input type="text" class="form-control" id="numeroMesa" name="numeroMesa" value="<?php echo $this->row['numeroMesa']; ?>">
	</div>
        
        <div class="form-group">
	    <label for="quantidade">Quantidade</label>
	    <input type="text" class="form-control" id="quantidade" name="quantidade" value="<?php echo $this->row['quantidade']; ?>">
	</div>
	
	
	
	<div class="form-group">
	    <label for="nomeCliente">Cliente</label>
    	<select class="form-control" id="id_cliente" name="id_cliente">
    		<option value="">Selecione</option>
    		<?php foreach($this->rowSetCliente as $rowCliente){ ?>
    			<option <?php echo $this->row['id_cliente'] == $rowCliente['id_cliente'] ? 'selected="selected"' : ''; ?> value="<?php echo $rowCliente['id_cliente']; ?>"><?php echo $rowCliente['nomeCliente']; ?></option>
    		<?php } ?>
    	</select>
	</div>
        
        <div class="form-group">
	    <label for="nomeGarcom">Garcom</label>
    	<select class="form-control" id="id_cliente" name="id_garcom">
    		<option value="">Selecione</option>
    		<?php foreach($this->rowSetGarcom as $rowGarcom){ ?>
    			<option <?php echo $this->row['id_garcom'] == $rowGarcom['id_garcom'] ? 'selected="selected"' : ''; ?> value="<?php echo $rowGarcom['id_garcom']; ?>"><?php echo $rowGarcom['nomeGarcom']; ?></option>
    		<?php } ?>
    	</select>
	</div>
      
	
	
	
	
	
	<div class="text-center">
		<input type="submit" value="Enviar" class="btn btn-success" />
		<a href="<?php echo $this->baseUrl('mesa/index'); ?>" class="btn btn-danger" >Voltar</a>
	</div>
</form>
