<meta charset="utf-8">
<h1>Calculo de Salário</h1>

<form method="post" action="<?php echo $this->baseUrl('funcionario/calcular-salario')?>">
    Nome do Funcionário: <input type="text" name="nome" /><br/><br/>
    
    Horas Trabalhadas: <input type="text" name="hora" /><br/>
    
    Valor da Hora: <input type="text" name="valor" /><br/>
    
    Qtde de Filhos: <input type="text" name="filhos" /><br/>
     
    <br/>
    <input type="submit" value="Enviar">
    
</form>
