<form method="post" action="<?php echo $this->baseUrl('funcionario/salario-final')?>">
    Nome do funcionario: <input type="text" name="nome" /><br/><br/>
    horas trabalhadas: <input type="text" name="horas" /><br />
    valor da hora: <input type="text" name="valor" /><br />
    quantidade de filhos: <input type="text" name="filho" /><br />
    
    <br/>
    <input type="submit" value="Salvar" />
    
</form>