<!DOCTYPE html>
<html>

<head>
    <title>Compras</title>

    <link href="<?php echo $this->baseUrl('js/bootstrap/css/bootstrap.min.css'); ?>" rel="stylesheet">

    <!-- Mainly scripts -->
    <script src="<?php echo $this->baseUrl('js/jquery-2.2.3.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('js/bootstrap/js/bootstrap.min.js'); ?>"></script>

    <?php echo $this->headScript(); ?>
</head>

<body>

 <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Compras</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Principal</a></li>
            <li><a href="<?php echo $this->baseUrl('perfil/index'); ?>">Perfil</a></li>
            <li><a href="<?php echo $this->baseUrl('usuario/index'); ?>">Usuário</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
	
	<div class="container"  style="margin-top: 60px;">
    	<?php echo $this->layout()->content; ?>
	</div>
</body>
</html>
