<h1>Media do Aluno</h1>

<form method="post" action="<?php echo $this->baseUrl('aluno/calcular-media')?>">
    Nome do Aluno: <input type="text" name="nome" /><br/><br/>
    
    Nota 1: <input type="text" name="n1" /><br/>
    Nota 2: <input type="text" name="n2" /><br/>
    Nota 3: <input type="text" name="n3" /><br/> 
    Nota 4: <input type="text" name="n4" /><br/>
     
    <br/>
    <input type="submit" value="Enviar">
    
</form>







