<h1>Listagem de Produto</h1>

<a href="<?php echo $this->baseUrl('produto/formulario'); ?>" class="btn btn-success">Inserir</a>

<table border="1" width="100%" class="table table-striped">
	<tr>
		<td>Ações</td>
		<td>Id</td>
		<td>Nome</td>
		<td>Preco</td>
	</tr>
	<?php foreach($this->rowSet as $row){ ?>
		<tr>
			<td>
				<a href="<?php echo $this->baseUrl('produto/formulario/id_produto/' . $row['id_produto']); ?>" class="btn btn-warning">Alterar</a>
				<a href="<?php echo $this->baseUrl('produto/excluir/id_produto/' . $row['id_produto']); ?>" class="btn btn-danger">Excluir</a>
			</td>
			<td><?php echo $row['id_produto']; ?></td>
			<td><?php echo $row['nomeProduto']; ?></td>
			<td><?php echo $row['preco']; ?></td>
		</tr>
	<?php } ?>
</table>