<h1>Mesas</h1>

<form action="<?php echo $this->baseUrl('entregador/gravar'); ?>" method="post" enctype="multipart/form-data">
	<input type="hidden" name="id_entregador" value="<?php echo $this->row['id_entregador']; ?>" />
	
	<div class="form-group">
	    <label for="nome">Nome</label>
	    <input type="text" class="form-control" id="entrega" name="nome" value="<?php echo $this->row['nome']; ?>">
	</div>
	
        <div class="form-group">
	    <label for="telefone">Telefone</label>
	    <input type="text" class="form-control" id="telefone" name="telefone" value="<?php echo $this->row['telefone']; ?>">
	</div>
	
	
	<div class="text-center">
		<input type="submit" value="Enviar" class="btn btn-success" />
		<a href="<?php echo $this->baseUrl('entregador/index'); ?>" class="btn btn-danger" >Voltar</a>
	</div>
</form>
<script>
    $(function(){
        
        $('#id_uf').change(function(){
            $('#div_municipios').load('<?php echo $this->baseUrl('usuario/carregar-municipio/id_uf/'); ?>' + $('#id_uf').val());
        });
        
    });    
</script>