<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Lanchonete noleto</title>

    <link href="<?php echo $this->baseUrl('js/bootstrap/css/bootstrap.min.css'); ?>" rel="stylesheet">

    <!-- Mainly scripts -->
    <script src="<?php echo $this->baseUrl('js/jquery-2.2.3.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('js/bootstrap/js/bootstrap.min.js'); ?>"></script>

    <?php echo $this->headScript(); ?>
</head>

<body>

 <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="#">Lanchonete</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Principal</a></li>
            <!--<li><a href="<?php echo $this->baseUrl('perfil/index'); ?>">Perfil</a></li>-->
            <li><a href="<?php echo $this->baseUrl('usuario/index'); ?>">Usuário</a></li>
            <li><a href="<?php echo $this->baseUrl('produto/index'); ?>">Produto</a></li>
            <li><a href="<?php echo $this->baseUrl('mesa/index'); ?>">Mesas</a></li>
            <li><a href="<?php echo $this->baseUrl('cliente/index'); ?>">Cliente</a></li>
            <li><a href="<?php echo $this->baseUrl('garcom/index'); ?>">Garçom</a></li>
            <li><a href="<?php echo $this->baseUrl('caixa/index'); ?>">Caixa</a></li>
            <li><a href="<?php echo $this->baseUrl('entregador/index'); ?>">Entregador</a></li>
            
          </ul>
        <ul class="nav navbar-nav navbar-right">
            <?php if(empty($_SESSION['id_usuario'])){ ?>
            <li><a href="<?php echo $this->baseUrl('usuario/login'); ?>">Login</a></li>
            <?php } else { ?>
            <li><a><img width="30px" src="<?php echo $this->baseUrl('img/fotos/' . (!empty($_SESSION['foto']) ? $_SESSION['foto'] : 'semfoto.jpg' ));  ?>" class="img-circle" alt="Circular Image"> Bem vindo, <?php echo $_SESSION['nome']; ?> </a></li>
            <li><a href="<?php echo $this->baseUrl('usuario/logaut'); ?>">Sair</a></li>
            <?php } ?>
        </ul>
        </div><!--/.nav-collapse -->
        
      </div>
    </nav>
	
	<div class="container"  style="margin-top: 60px;">
    	<?php echo $this->layout()->content; ?>
	</div>
</body>
</html>
